version: "3.8"
services:
  db:
    container_name: mongodb
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root-h9BcipiGGnfuhnGW
      MONGO_INITDB_ROOT_PASSWORD: zZ4NP1J9JZGunzOfyUCuG6fI
      DB_NAME: palette-board
      DB_USER: user-2OCHv6OaBxQyFsul
      DB_PASSWORD: gRU9SvlKLaRGc5AL
    volumes:
      - db-data:/data/db
      - ./docker/mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    networks:
      - app-network

  api:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: palette-board
      DB_USER: user-2OCHv6OaBxQyFsul
      DB_PASS: gRU9SvlKLaRGc5AL
    container_name: node-server
    depends_on:
      - db
    volumes:
      - .:/home/node/app
    networks:
      - app-network
    ports:
      - "5000:5000"
  nextjs:
    container_name: nextjs
    build:
      context: ../website
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../website:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - 3000:3000
    networks:
      - app-network
    environment:
      API_HOST: api
      API_PORT: 5000
    depends_on:
      - api

networks:
  app-network:
    external:
      name: nginx-network

volumes:
  db-data: